### ISSUE TITLE
Dependency issue

### ISSUE THREAD

**Issue by NickJorens** [SundaeSwap-finance/sundae-sdk#13]
I've been getting an error about dependencies since alpha.23.
`npm ERR! Found: @sundaeswap/asset@0.6.9
npm ERR! node_modules/@sundaeswap/asset
npm ERR!   peer @sundaeswap/asset@"^0.6.9" from @sundaeswap/sdk-core@0.2.0-alpha.25
npm ERR!   node_modules/@sundaeswap/sdk-core
npm ERR!     @sundaeswap/sdk-core@"^0.2.0-alpha.25" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @sundaeswap/asset@"^0.5.9" from @sundaeswap/cpp@0.6.8
npm ERR! node_modules/@sundaeswap/cpp
npm ERR!   peer @sundaeswap/cpp@"^0.6.7" from @sundaeswap/sdk-core@0.2.0-alpha.25
npm ERR!   node_modules/@sundaeswap/sdk-core
npm ERR!     @sundaeswap/sdk-core@"^0.2.0-alpha.25" from the root project`

I can still continue by doing a --force, but that's not ideal.

**Comment by cjkoepke** [comment]
Hey @NickJorens, can you update to `0.2.0-alpha.26` and let me know if the issue is resolved?

**Comment by NickJorens** [comment]
Hi @cjkoepke,

This has fixed the issue for me. Thank you
