### ISSUE TITLE
Get all pools

### ISSUE THREAD

**Issue by NickJorens** [SundaeSwap-finance/sundae-sdk#14]
Hi,

Is there currently no way of retrieving all pools?
I've gone through the docs, but I can't seem to find it.

**Comment by cjkoepke** [comment]
Hey @NickJorens, sorry for the delay on this — I'm just now seeing this issue. This could be added very easily here: https://github.com/SundaeSwap-finance/sundae-sdk/blob/main/packages/core/src/classes/Extensions/QueryProviders/QueryProvider.SundaeSwap.ts

I'll try and get to it soon, but feel free to open a PR if you'd like.
